# Generated by Django 5.0.2 on 2024-06-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0015_delete_store_exchange_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substances',
            name='id',
        ),
        migrations.AlterField(
            model_name='substances',
            name='source',
            field=models.JSONField(blank=True, primary_key=True, serialize=False),
        ),
    ]
