# Generated by Django 5.0.2 on 2024-06-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0016_remove_substances_id_alter_substances_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substances',
            name='last_modified',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
