# Generated by Django 5.0.2 on 2024-06-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0017_alter_substances_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='substances',
            name='ID',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substances',
            name='source',
            field=models.JSONField(blank=True),
        ),
    ]
