# Generated by Django 5.0.2 on 2024-06-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0019_alter_substances_cas_num_alter_substances_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substances',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substances',
            name='last_modified',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='substances',
            name='version',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
    ]
